### ISSUE TITLE
1.3.2 还是有出现错乱问题 

### ISSUE THREAD

**Issue by SjonC** [QuintGao/GKVideoScrollView#5]
在结束滑动时显示的cell，不对，这里获取到的 cell 是ctrCell， 实际上展现的 cell是 btmcell，
- (void)scrollView:(GKVideoScrollView *)scrollView didEndScrollingCell:(GKVideoViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath;

我用下面方式判断获取到的cell 并没有展示在屏幕上
- (BOOL)isViewVisibleInScrollView:(UIView *)view scrollView:(UIScrollView *)scrollView {
    CGRect viewRect = [view convertRect:view.bounds toView:scrollView];

    CGRect scrollViewVisibleRect = CGRectMake(scrollView.contentOffset.x,
                                              scrollView.contentOffset.y,
                                              scrollView.bounds.size.width,
                                              scrollView.bounds.size.height);

    return CGRectIntersectsRect(scrollViewVisibleRect, viewRect);
}

**Comment by QuintGao** [comment]
什么场景下出现的？

**Comment by SjonC** [comment]
调用 - (void)reloadDataWithIndex:(NSInteger)index;  后上滑就容易出现

**Comment by QuintGao** [comment]
没复现，能提供demo吗

**Comment by SjonC** [comment]
[GKVideoScrollViewDemo.zip](https://github.com/QuintGao/GKVideoScrollView/files/13911296/GKVideoScrollViewDemo.zip)
复现 demo

**Comment by QuintGao** [comment]
没问题的哈，只是didEndScrollingCell这个方法回调的比较快，UIScrollView的位置还没修复，实际显示的cell还是回调的那个cell

**Comment by SjonC** [comment]
我这里测得 didEndScrollingCell 获取的 cell 是已经上滑了的 cell ， 那不就是 不是实际显示的 cell 了么，

**Comment by SjonC** [comment]
我在didEndScrollingCell 里执行视频播放处理就会变成了已经上滑了的 cell 还在播放

**Comment by QuintGao** [comment]
[GKVideoScrollViewDemo.zip](https://github.com/QuintGao/GKVideoScrollView/files/13915825/GKVideoScrollViewDemo.zip)
再试试

**Comment by SjonC** [comment]
解决了 👍🏻👍🏻
